### ISSUE TITLE
Releasing 0efd6951fe9966b5e1139452bf31d0610fd4452b

### ISSUE THREAD

**Issue by kidrahahjo** [woile/starlette-apispec#60]
Hello Maintainers, first of all, thank you for creating this package. It has really been a useful tool for us! 

We're currently facing an issue which would be solved by simply releasing the commit 0efd6951fe9966b5e1139452bf31d0610fd4452b. Installation for pyyaml 5.4.1 breaks which is not letting us install starlette-apispec without pinning pyyaml to a lower version. Would it be possible for maintainers to release the bumped dependency?

Thank you!

**Comment by woile** [comment]
`v2.0` has been released 🎉 I had to drop support for older python versions on the way

**Comment by kidrahahjo** [comment]
Thank you so much!
